rate_limit:
  ips:
    - ip: "192.168.1.1"
      limit: 10
    - ip: "192.168.1.2"
      limit: 15
  tokens:
    - token: "tokenzinho"
      limit: 2
      expiration: 5
      block: 10
    - token: "tokend"
      limit: 25